Repository IT-Cotato/10th-ODIT-BE, pull requests merged in 2024-12, with the labels that each got.

#3 [FEAT] PR 템플릿 작성
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔧 Chore, ⚙️ Setting

#6 [Feat] 전체 entity 구현 완료 & 연관관계 설정
  src/main/java/com/adit/backend/domain/commonPlace/entity/CommonPlace.java
  src/main/java/com/adit/backend/domain/event/entity/Event.java
  src/main/java/com/adit/backend/domain/friendRelationship/entity/FriendRelationship.java
  src/main/java/com/adit/backend/domain/image/entity/Image.java
  src/main/java/com/adit/backend/domain/notification/entity/Notification.java
  src/main/java/com/adit/backend/domain/placeStatistic/entity/PlaceStatistics.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/userPlace/entity/UserPlace.java
  src/main/java/com/adit/backend/global/entity/BaseEntity.java
Labels: ✨ Feat

#7 [Feat] 에러 코드와 공통 예외 처리 구현
  src/main/java/com/adit/global/error/ErrorResponse.java
  src/main/java/com/adit/global/error/GlobalExceptionHandler.java
  src/main/java/com/adit/global/error/exception/BusinessException.java
  src/main/java/com/adit/global/error/exception/ErrorCode.java
  src/main/java/com/adit/global/error/exception/GlobalErrorCode.java
Labels: ✨ Feat

#12 [Feat] 카카오 소셜 로그인 및 JWT 인증 시스템 구현
  build.gradle
  src/main/java/com/adit/backend/domain/auth/controller/AuthController.java
  src/main/java/com/adit/backend/domain/auth/dto/OAuth2UserInfo.java
  src/main/java/com/adit/backend/domain/auth/dto/request/KakaoRequest.java
  src/main/java/com/adit/backend/domain/auth/dto/response/KakaoResponse.java
  src/main/java/com/adit/backend/domain/auth/entity/Token.java
  src/main/java/com/adit/backend/domain/auth/repository/TokenRepository.java
  src/main/java/com/adit/backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/adit/backend/domain/auth/service/command/TokenCommandService.java
  src/main/java/com/adit/backend/domain/auth/service/query/TokenQueryService.java
  src/main/java/com/adit/backend/domain/image/service/ImageService.java
  src/main/java/com/adit/backend/domain/place/service/CommonPlaceService.java
  src/main/java/com/adit/backend/domain/user/controller/UserController.java
  src/main/java/com/adit/backend/domain/user/converter/UserConverter.java
  src/main/java/com/adit/backend/domain/user/dto/request/UserRequest.java
  src/main/java/com/adit/backend/domain/user/dto/response/UserResponse.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/user/enums/Role.java
  src/main/java/com/adit/backend/domain/user/enums/SocialType.java
  src/main/java/com/adit/backend/domain/user/exception/UserException.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetails.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetailsService.java
  src/main/java/com/adit/backend/domain/user/repository/UserRepository.java
  src/main/java/com/adit/backend/domain/user/service/FriendshipService.java
  src/main/java/com/adit/backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/adit/backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/adit/backend/global/config/AppConfig.java
  src/main/java/com/adit/backend/global/config/CorsConfig.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/java/com/adit/backend/global/config/SwaggerConfig.java
  src/main/java/com/adit/backend/global/error/ErrorCode.java
  src/main/java/com/adit/backend/global/error/ErrorResponse.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/adit/backend/global/error/exception/BusinessException.java
  src/main/java/com/adit/backend/global/error/exception/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/error/exception/TokenException.java
  src/main/java/com/adit/backend/global/security/jwt/exception/AuthException.java
  src/main/java/com/adit/backend/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adit/backend/global/security/jwt/filter/TokenExceptionFilter.java
  src/main/java/com/adit/backend/global/security/jwt/handler/CustomAccessDeniedHandler.java
  src/main/java/com/adit/backend/global/security/jwt/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/adit/backend/global/security/jwt/service/JwtTokenService.java
  src/main/java/com/adit/backend/global/security/jwt/util/JwtTokenProvider.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/adit/backend/global/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/adit/backend/global/util/KeyGenerator.java
  src/main/java/com/adit/backend/global/util/TimeUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feat

#18 [Feat] CI/CD 구축
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ✨ Feat

#20 [Fix] CI/CD 구축 오류 해결
  .github/workflows/dev_deploy.yml
Labels: 🐛 Bug, 🚨 HotFix

#22 [Fix] CI/CD 배포를 위한 서버 환경설정 코드 수정 및 적용
  .github/ISSUE_TEMPLATE/bug-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/dev_deploy.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🔨 Fix, ⚙️ Setting

#24 [Fix] 쿠키 지정 오류 해결
  src/main/java/com/adit/backend/domain/auth/service/command/AuthCommandService.java
Labels: 🐛 Bug, 🔨 Fix
