Repository IT-Cotato/10th-ODIT-BE, pull requests merged in 2025-02, with the labels that each got.

#63 [Refactor] ExceptionHandler 구조 개선
  src/main/java/com/adit/backend/domain/ai/service/OpenAiService.java
  src/main/java/com/adit/backend/domain/auth/dto/OAuth2UserInfo.java
  src/main/java/com/adit/backend/domain/auth/exception/AuthException.java
  src/main/java/com/adit/backend/domain/auth/service/AuthService.java
  src/main/java/com/adit/backend/domain/event/exception/EventAlreadyExistsException.java
  src/main/java/com/adit/backend/domain/event/exception/EventCreationFailedException.java
  src/main/java/com/adit/backend/domain/event/exception/EventDeletionFailedException.java
  src/main/java/com/adit/backend/domain/event/exception/EventException.java
  src/main/java/com/adit/backend/domain/event/exception/EventNotFoundException.java
  src/main/java/com/adit/backend/domain/event/exception/EventUpdateFailedException.java
  src/main/java/com/adit/backend/domain/event/service/command/EventCommandService.java
  src/main/java/com/adit/backend/domain/event/service/query/EventQueryService.java
  src/main/java/com/adit/backend/domain/image/exception/ImageException.java
  src/main/java/com/adit/backend/domain/notification/exception/NotificationException.java
  src/main/java/com/adit/backend/domain/place/exception/CommonPlaceNotFoundException.java
  src/main/java/com/adit/backend/domain/place/exception/FriendNotFoundException.java
  src/main/java/com/adit/backend/domain/place/exception/NotValidException.java
  src/main/java/com/adit/backend/domain/place/exception/PlaceException.java
  src/main/java/com/adit/backend/domain/place/exception/UserPlaceNotFoundException.java
  src/main/java/com/adit/backend/domain/place/service/CommonPlaceCommandService.java
  src/main/java/com/adit/backend/domain/place/service/CommonPlaceQueryService.java
  src/main/java/com/adit/backend/domain/place/service/UserPlaceCommandService.java
  src/main/java/com/adit/backend/domain/place/service/UserPlaceQueryService.java
  src/main/java/com/adit/backend/domain/user/exception/FriendShipException.java
  src/main/java/com/adit/backend/domain/user/exception/UserException.java
  src/main/java/com/adit/backend/domain/user/exception/friend/FriendRequestNotFoundException.java
  src/main/java/com/adit/backend/domain/user/exception/user/NickNameNullException.java
  src/main/java/com/adit/backend/domain/user/exception/user/NickNameValidateException.java
  src/main/java/com/adit/backend/domain/user/exception/user/UserNotFoundException.java
  src/main/java/com/adit/backend/domain/user/service/command/FriendCommandService.java
  src/main/java/com/adit/backend/domain/user/service/query/FriendQueryService.java
  src/main/java/com/adit/backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/adit/backend/global/error/ErrorCode.java
  src/main/java/com/adit/backend/global/error/ErrorResponse.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/adit/backend/global/error/exception/BusinessException.java
  src/main/java/com/adit/backend/global/security/jwt/exception/TokenException.java
  src/main/java/com/adit/backend/global/security/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/com/adit/backend/global/security/jwt/filter/TokenExceptionFilter.java
  src/main/java/com/adit/backend/global/security/jwt/util/JwtTokenProvider.java
  src/main/java/com/adit/backend/infra/crawler/WebContentCrawler.java
  src/main/java/com/adit/backend/infra/crawler/common/AbstractWebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/exception/CrawlingException.java
  src/main/java/com/adit/backend/infra/crawler/platform/BrunchCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/GenericWebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/InstagramCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/NaverCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/TistoryCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/service/WebContentCrawlingService.java
  src/main/java/com/adit/backend/infra/oauth/KakaoOAuthService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ♻️ Refactor

#70 특정 플랫폼 이미지 추출 및 저장 오류 해결
  build.gradle
  src/main/java/com/adit/backend/domain/image/controller/ImageController.java
  src/main/java/com/adit/backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/adit/backend/global/util/ImageUtil.java
  src/main/java/com/adit/backend/infra/s3/service/AwsS3Service.java
Labels: 🐛 Bug, 🔨 Fix

#72 [Fix] JWT 토큰 검증 로직 개선
  src/main/java/com/adit/backend/domain/auth/service/AuthService.java
  src/main/java/com/adit/backend/global/security/jwt/enums/TokenStatus.java
  src/main/java/com/adit/backend/global/security/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/com/adit/backend/global/security/jwt/util/JwtTokenProvider.java
Labels: 🐛 Bug, 🔨 Fix

#74 [Feat] 이미지 업로드 비동기 처리 및 CommonEvent 엔티티 개선
  build.gradle
  src/main/java/com/adit/backend/domain/event/entity/CommonEvent.java
  src/main/java/com/adit/backend/domain/image/enums/Directory.java
  src/main/java/com/adit/backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetailsService.java
  src/main/java/com/adit/backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/adit/backend/global/config/AsyncConfig.java
  src/main/java/com/adit/backend/global/util/ImageUtil.java
  src/main/java/com/adit/backend/infra/s3/service/AwsS3Service.java
Labels: ✨ Feat

#77 [Refactor] 장소, 이벤트 관련 이미지 저장 로직 수정
  .github/workflows/dev_deploy.yml
  src/main/java/com/adit/backend/domain/ai/service/OpenAiService.java
  src/main/java/com/adit/backend/domain/ai/util/LoggingAdvisor.java
  src/main/java/com/adit/backend/domain/event/converter/CommonEventConverter.java
  src/main/java/com/adit/backend/domain/event/converter/UserEventConverter.java
  src/main/java/com/adit/backend/domain/event/dto/response/EventResponseDto.java
  src/main/java/com/adit/backend/domain/event/service/command/CommonEventCommandService.java
  src/main/java/com/adit/backend/domain/event/service/command/UserEventCommandService.java
  src/main/java/com/adit/backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/adit/backend/domain/place/converter/CommonPlaceConverter.java
  src/main/java/com/adit/backend/domain/place/converter/UserPlaceConverter.java
  src/main/java/com/adit/backend/domain/place/dto/response/PlaceResponseDto.java
  src/main/java/com/adit/backend/domain/place/service/command/CommonPlaceCommandService.java
  src/main/java/com/adit/backend/domain/place/service/command/UserPlaceCommandService.java
  src/main/java/com/adit/backend/global/config/AiConfig.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/resources/application.yml
Labels: ♻️ Refactor

#79 [Feat] 이벤트 API 기능 추가
  src/main/java/com/adit/backend/domain/event/controller/EventController.java
  src/main/java/com/adit/backend/domain/event/entity/EventStatistics.java
  src/main/java/com/adit/backend/domain/event/repository/EventStatisticsRepository.java
  src/main/java/com/adit/backend/domain/event/service/command/UserEventCommandService.java
  src/main/java/com/adit/backend/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/adit/backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/adit/backend/domain/place/service/command/UserPlaceCommandService.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/infra/s3/service/AwsS3Service.java
Labels: ✨ Feat

#73 [Feat] 장소 API 기능 보완
  src/main/java/com/adit/backend/domain/image/converter/ImageConverter.java
  src/main/java/com/adit/backend/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/adit/backend/domain/image/repository/ImageRepository.java
  src/main/java/com/adit/backend/domain/place/controller/PlaceController.java
  src/main/java/com/adit/backend/domain/place/converter/CommonPlaceConverter.java
  src/main/java/com/adit/backend/domain/place/entity/PlaceStatistics.java
  src/main/java/com/adit/backend/domain/place/repository/PlaceStatisticsRepository.java
  src/main/java/com/adit/backend/domain/place/repository/UserPlaceRepository.java
  src/main/java/com/adit/backend/domain/place/service/command/PlaceStatisticsCommandService.java
  src/main/java/com/adit/backend/domain/place/service/command/UserPlaceCommandService.java
  src/main/java/com/adit/backend/domain/place/service/query/CommonPlaceQueryService.java
  src/main/java/com/adit/backend/domain/place/service/query/UserPlaceQueryService.java
  src/main/java/com/adit/backend/domain/user/controller/UserController.java
  src/main/java/com/adit/backend/domain/user/converter/UserConverter.java
  src/main/java/com/adit/backend/domain/user/dto/response/UserResponse.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/adit/backend/domain/user/service/query/FriendQueryService.java
  src/main/java/com/adit/backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/resources/application-dev.yml
Labels: ✨ Feat

#84 [Fix] EC2 배포 시 기존 프로세스 종료 미완료 문제 개선
  .github/workflows/dev_deploy.yml
  src/main/resources/application-dev.yml
Labels: 🔨 Fix

#91 ✨ [Feat] SSE + Redis pub/sub를 이용한 알림 기능 구현 완료
  .github/workflows/dev_deploy.yml
  src/main/java/com/adit/backend/domain/auth/service/AuthService.java
  src/main/java/com/adit/backend/domain/event/entity/UserEvent.java
  src/main/java/com/adit/backend/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/adit/backend/domain/notification/constants/Channel.java
  src/main/java/com/adit/backend/domain/notification/constants/MsgFormat.java
  src/main/java/com/adit/backend/domain/notification/controller/DemoDayController.java
  src/main/java/com/adit/backend/domain/notification/controller/NotificationController.java
  src/main/java/com/adit/backend/domain/notification/converter/NotificationConverter.java
  src/main/java/com/adit/backend/domain/notification/converter/NotificationEventConverter.java
  src/main/java/com/adit/backend/domain/notification/dto/NotificationResponse.java
  src/main/java/com/adit/backend/domain/notification/entity/Notification.java
  src/main/java/com/adit/backend/domain/notification/enums/NotificationType.java
  src/main/java/com/adit/backend/domain/notification/event/NotificationEvent.java
  src/main/java/com/adit/backend/domain/notification/event/NotificationEventHandler.java
  src/main/java/com/adit/backend/domain/notification/event/NotificationEventPublisher.java
  src/main/java/com/adit/backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/adit/backend/domain/notification/repository/SseEmitterRepository.java
  src/main/java/com/adit/backend/domain/notification/service/NotificationDemoDayService.java
  src/main/java/com/adit/backend/domain/notification/service/NotificationGenerationService.java
  src/main/java/com/adit/backend/domain/notification/service/RedisMessageService.java
  src/main/java/com/adit/backend/domain/notification/service/SseEmitterService.java
  src/main/java/com/adit/backend/domain/notification/service/command/NotificationCommandService.java
  src/main/java/com/adit/backend/domain/notification/service/handler/RedisSubscriber.java
  src/main/java/com/adit/backend/domain/notification/service/query/NotificationQueryService.java
  src/main/java/com/adit/backend/domain/place/controller/PlaceController.java
  src/main/java/com/adit/backend/domain/place/repository/PlaceStatisticsRepository.java
  src/main/java/com/adit/backend/domain/place/repository/UserPlaceRepository.java
  src/main/java/com/adit/backend/domain/place/service/command/PlaceStatisticsCommandService.java
  src/main/java/com/adit/backend/domain/place/service/command/UserPlaceCommandService.java
  src/main/java/com/adit/backend/domain/place/service/query/CommonPlaceQueryService.java
  src/main/java/com/adit/backend/domain/place/service/query/UserPlaceQueryService.java
  src/main/java/com/adit/backend/domain/user/dto/request/FriendRequestDto.java
  src/main/java/com/adit/backend/domain/user/dto/response/FriendshipResponseDto.java
  src/main/java/com/adit/backend/domain/user/service/command/FriendCommandService.java
  src/main/java/com/adit/backend/global/config/AsyncConfig.java
  src/main/java/com/adit/backend/global/config/CorsConfig.java
  src/main/java/com/adit/backend/global/config/RedisConfig.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/adit/backend/global/util/CookieUtils.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ✨ Feat

#93 [Refactor] 이미지 추출 정확도 향상, 서비스 중단 방지 적용
  src/main/java/com/adit/backend/infra/crawler/WebContentCrawler.java
Labels: ♻️ Refactor

#96 [Fix] 프론트 로컬 환경 소셜 로그인 호환 적용
  src/main/java/com/adit/backend/domain/auth/controller/AuthController.java
  src/main/java/com/adit/backend/domain/auth/service/AuthService.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/java/com/adit/backend/global/config/SwaggerConfig.java
  src/main/java/com/adit/backend/infra/oauth/KakaoOAuthService.java
Labels: 🐛 Bug, 🔨 Fix

#95 [Refactor] 이벤트 수정 API 로직 분리 진행
  src/main/java/com/adit/backend/domain/event/controller/EventController.java
  src/main/java/com/adit/backend/domain/event/entity/UserEvent.java
  src/main/java/com/adit/backend/domain/event/service/EventImageService.java
  src/main/java/com/adit/backend/domain/event/service/command/UserEventCommandService.java
  src/main/java/com/adit/backend/domain/image/dto/request/ImageUpdateRequestDto.java
  src/main/java/com/adit/backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
Labels: ♻️ Refactor

#99 [Refactor] 친구 API 응답값 수정
  src/main/java/com/adit/backend/domain/user/controller/FriendshipController.java
  src/main/java/com/adit/backend/domain/user/dto/response/FriendRequestResponseDto.java
  src/main/java/com/adit/backend/domain/user/service/query/FriendQueryService.java
Labels: ♻️ Refactor

#101 [Feat] 북마크 장소저장 API 기능 구현
  src/main/java/com/adit/backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/adit/backend/domain/place/controller/PlaceController.java
  src/main/java/com/adit/backend/domain/place/converter/UserPlaceConverter.java
  src/main/java/com/adit/backend/domain/place/service/command/UserPlaceCommandService.java
Labels: ✨ Feat

#102 [Refactor] 장소 이미지 관련 API 수정 및 추가
  src/main/java/com/adit/backend/domain/place/controller/PlaceController.java
  src/main/java/com/adit/backend/domain/place/service/PlaceImageService.java
Labels: ♻️ Refactor

#107 [Fix] 친구 요청 중복 및 상태 확인 로직 추가 및 설정 업데이트
  src/main/java/com/adit/backend/domain/image/repository/ImageRepository.java
  src/main/java/com/adit/backend/domain/user/controller/UserController.java
  src/main/java/com/adit/backend/domain/user/repository/FriendshipRepository.java
  src/main/java/com/adit/backend/domain/user/service/command/FriendCommandService.java
  src/main/java/com/adit/backend/domain/user/service/query/FriendQueryService.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/resources/application-dev.yml
Labels: 🐛 Bug, 🔨 Fix
