Repository IT-Cotato/10th-ODIT-BE, pull requests merged in 2025-05, with the labels that each got.

#128 [Fix] 소셜 로그인 관련 환경변수 추가
  .github/workflows/docker_deploy.yml
Labels: 🐛 Bug

#132 [Refactor] 카카오 소셜 로그인 시, 프로필 추출 로직 수정
  .github/workflows/docker_deploy.yml
  src/main/java/com/adit/backend/domain/auth/service/KakaoOAuth2UserService.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ♻️ Refactor

#134 [Fix] Blue/Green Docker 배포 최적화 - CPU 과부하 문제 해결
  .github/workflows/docker_deploy.yml
Labels: 🐛 Bug

#136 [Fix] 소셜 로그인 리다이렉트 주소 관련 설정
  .github/workflows/docker_deploy.yml
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🐛 Bug

#142 [Fix] HttpCookieOAuth2AuthorizationRequestRepository 을 사용하여 쿠키 기반 저장 방식으로 변경
  src/main/java/com/adit/backend/domain/auth/handler/DelegatingOAuth2LoginSuccessHandler.java
  src/main/java/com/adit/backend/domain/auth/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/adit/backend/domain/auth/util/CookieUtils.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
Labels: 🔨 Fix
