Repository IT-Cotato/10th-ODIT-BE, pull requests merged in 2025-01, with the labels that each got.

#32 [Feat] 이벤트(전시/공연) API 구현 완료
  src/main/java/com/adit/backend/domain/event/controller/EventController.java
  src/main/java/com/adit/backend/domain/event/converter/EventConverter.java
  src/main/java/com/adit/backend/domain/event/dto/request/EventRequestDto.java
  src/main/java/com/adit/backend/domain/event/dto/request/EventUpdateRequestDto.java
  src/main/java/com/adit/backend/domain/event/dto/response/EventResponseDto.java
  src/main/java/com/adit/backend/domain/event/entity/Event.java
  src/main/java/com/adit/backend/domain/event/exception/EventAlreadyExistsException.java
  src/main/java/com/adit/backend/domain/event/exception/EventCreationFailedException.java
  src/main/java/com/adit/backend/domain/event/exception/EventDeletionFailedException.java
  src/main/java/com/adit/backend/domain/event/exception/EventNotFoundException.java
  src/main/java/com/adit/backend/domain/event/exception/EventUpdateFailedException.java
  src/main/java/com/adit/backend/domain/event/repository/EventRepository.java
  src/main/java/com/adit/backend/domain/event/service/command/EventCommandService.java
  src/main/java/com/adit/backend/domain/event/service/query/EventQueryService.java
  src/main/java/com/adit/backend/domain/scraper/controller/scraperController.java
  src/main/java/com/adit/backend/domain/scraper/service/scraperService.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/error/GlobalExceptionHandler.java
Labels: ✨ Feat

#36 Fix : Event 관련 에러 GlobalExceptionHandler에서 일시적 등록 해제
  src/main/java/com/adit/backend/domain/event/service/query/EventQueryService.java
  src/main/java/com/adit/backend/global/error/GlobalExceptionHandler.java
Labels: 🔨 Fix

#37 [Feat] OpenAI API를 이용한 링크 요약 시스템 구현 완료
  build.gradle
  src/main/java/com/adit/backend/domain/ai/controller/OpenAiController.java
  src/main/java/com/adit/backend/domain/ai/dto/request/ContentExtractionRequest.java
  src/main/java/com/adit/backend/domain/ai/dto/response/ContentListResponse.java
  src/main/java/com/adit/backend/domain/ai/dto/response/ContentResponse.java
  src/main/java/com/adit/backend/domain/ai/dto/response/CrawlCompletionResponse.java
  src/main/java/com/adit/backend/domain/ai/enums/ContentType.java
  src/main/java/com/adit/backend/domain/ai/exception/AiException.java
  src/main/java/com/adit/backend/domain/ai/service/ContentService.java
  src/main/java/com/adit/backend/domain/ai/service/OpenAiService.java
  src/main/java/com/adit/backend/domain/ai/util/LoggingAdvisor.java
  src/main/java/com/adit/backend/global/annotation/StringFile.java
  src/main/java/com/adit/backend/global/config/AiConfig.java
  src/main/java/com/adit/backend/global/config/AsyncConfig.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/util/TimeUtil.java
  src/main/java/com/adit/backend/infra/crawler/WebContentCrawler.java
  src/main/java/com/adit/backend/infra/crawler/common/AbstractWebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/common/WebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/exception/CrawlingException.java
  src/main/java/com/adit/backend/infra/crawler/platform/BrunchCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/GenericWebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/NaverCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/TistoryCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/service/WebContentCrawlingService.java
  src/main/resources/application.yml
  src/main/resources/prompts/culture-info-example.st
  src/main/resources/prompts/culture-info-prompt.st
  src/main/resources/prompts/culture-info-system.st
Labels: ✨ Feat

#41 [Fix] CORS 설정 업데이트
  src/main/java/com/adit/backend/global/config/CorsConfig.java
Labels: 🚨 HotFix

#44 [Feat] 인스타그램 플랫폼 AI 요약 기능 구현
  src/main/java/com/adit/backend/domain/scraper/controller/scraperController.java
  src/main/java/com/adit/backend/domain/scraper/dto/response/scraperResponse.java
  src/main/java/com/adit/backend/domain/scraper/exception/scraperException.java
  src/main/java/com/adit/backend/infra/crawler/common/AbstractWebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/common/WebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/GenericWebCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/platform/InstagramCrawlingStrategy.java
  src/main/java/com/adit/backend/infra/crawler/service/WebContentCrawlingService.java
Labels: ✨ Feat

#48 [Fix] Apify API 에서 이미지 가져오기
  src/main/java/com/adit/backend/infra/crawler/platform/InstagramCrawlingStrategy.java
Labels: 🔨 Fix

#51 [Feat] JWT를 이용한 사용자 토큰 발급 구현
  .github/workflows/dev_deploy.yml
  src/main/java/com/adit/backend/domain/auth/controller/AuthController.java
  src/main/java/com/adit/backend/domain/auth/dto/OAuth2UserInfo.java
  src/main/java/com/adit/backend/domain/auth/dto/request/LogoutRequest.java
  src/main/java/com/adit/backend/domain/auth/dto/response/ReissueResponse.java
  src/main/java/com/adit/backend/domain/auth/entity/Token.java
  src/main/java/com/adit/backend/domain/auth/repository/TokenRepository.java
  src/main/java/com/adit/backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/adit/backend/domain/auth/service/command/TokenCommandService.java
  src/main/java/com/adit/backend/domain/auth/service/query/TokenQueryService.java
  src/main/java/com/adit/backend/domain/user/converter/UserConverter.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetails.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetailsService.java
  src/main/java/com/adit/backend/domain/user/repository/UserRepository.java
  src/main/java/com/adit/backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/java/com/adit/backend/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adit/backend/global/security/jwt/service/JwtTokenService.java
  src/main/java/com/adit/backend/global/security/jwt/util/JwtTokenProvider.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/adit/backend/global/security/oauth/service/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: ✨ Feat

#54 [Feat] Redis 토큰 관리 구현 완료
  build.gradle
  src/main/java/com/adit/backend/domain/auth/annotation/LogoutResponse.java
  src/main/java/com/adit/backend/domain/auth/annotation/RefreshTokenCookie.java
  src/main/java/com/adit/backend/domain/auth/annotation/ReissueTokenResponse.java
  src/main/java/com/adit/backend/domain/auth/controller/AuthController.java
  src/main/java/com/adit/backend/domain/auth/dto/OAuth2UserInfo.java
  src/main/java/com/adit/backend/domain/auth/dto/response/KakaoResponse.java
  src/main/java/com/adit/backend/domain/auth/entity/Token.java
  src/main/java/com/adit/backend/domain/auth/repository/TokenRepository.java
  src/main/java/com/adit/backend/domain/auth/service/AuthService.java
  src/main/java/com/adit/backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/adit/backend/domain/auth/service/command/TokenCommandService.java
  src/main/java/com/adit/backend/domain/auth/service/query/TokenQueryService.java
  src/main/java/com/adit/backend/domain/user/annotation/ChangeNicknameApiSpec.java
  src/main/java/com/adit/backend/domain/user/annotation/DuplicateNicknameResponse.java
  src/main/java/com/adit/backend/domain/user/annotation/SuccessNicknameResponse.java
  src/main/java/com/adit/backend/domain/user/controller/UserController.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetailsService.java
  src/main/java/com/adit/backend/domain/user/repository/UserRepository.java
  src/main/java/com/adit/backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/adit/backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/adit/backend/global/annotation/ForbiddenResponse.java
  src/main/java/com/adit/backend/global/annotation/UnauthorizedResponse.java
  src/main/java/com/adit/backend/global/config/RedisConfig.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/java/com/adit/backend/global/config/SwaggerConfig.java
  src/main/java/com/adit/backend/global/security/jwt/entity/BlackList.java
  src/main/java/com/adit/backend/global/security/jwt/entity/RefreshToken.java
  src/main/java/com/adit/backend/global/security/jwt/entity/Token.java
  src/main/java/com/adit/backend/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adit/backend/global/security/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/com/adit/backend/global/security/jwt/repository/BlackListRepository.java
  src/main/java/com/adit/backend/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/adit/backend/global/security/jwt/service/JwtTokenService.java
  src/main/java/com/adit/backend/global/security/jwt/util/JwtTokenProvider.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feat

#57 [Feat] S3 이미지 업로드 기능 구현
  .github/workflows/dev_deploy.yml
  src/main/java/com/adit/backend/global/config/S3Config.java
  src/main/java/com/adit/backend/infra/s3/AwsS3Controller.java
  src/main/java/com/adit/backend/infra/s3/AwsS3Service.java
  src/main/resources/application.yml
Labels: ✨ Feat

#58 [Fix] 토큰 발급 인증 문제 해결
  .github/workflows/dev_deploy.yml
  src/main/java/com/adit/backend/domain/auth/service/AuthService.java
  src/main/java/com/adit/backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/adit/backend/global/config/SecurityConfig.java
  src/main/java/com/adit/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/adit/backend/global/security/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/adit/backend/global/util/CookieUtils.java
  src/main/resources/application.yml
Labels: 🐛 Bug

#55 [Feat] 친구 기능 구현
  src/main/java/com/adit/backend/domain/event/entity/Event.java
  src/main/java/com/adit/backend/domain/place/controller/PlaceController.java
  src/main/java/com/adit/backend/domain/place/entity/UserPlace.java
  src/main/java/com/adit/backend/domain/place/service/CommonPlaceQueryService.java
  src/main/java/com/adit/backend/domain/place/service/UserPlaceCommandService.java
  src/main/java/com/adit/backend/domain/user/controller/FriendshipController.java
  src/main/java/com/adit/backend/domain/user/converter/FriendConverter.java
  src/main/java/com/adit/backend/domain/user/converter/UserConverter.java
  src/main/java/com/adit/backend/domain/user/dto/response/FriendshipResponseDto.java
  src/main/java/com/adit/backend/domain/user/entity/Friendship.java
  src/main/java/com/adit/backend/domain/user/entity/User.java
  src/main/java/com/adit/backend/domain/user/exception/UserException.java
  src/main/java/com/adit/backend/domain/user/exception/friend/FriendRequestNotFoundException.java
  src/main/java/com/adit/backend/domain/user/exception/user/NickNameNullException.java
  src/main/java/com/adit/backend/domain/user/exception/user/NickNameValidateException.java
  src/main/java/com/adit/backend/domain/user/exception/user/UserNotFoundException.java
  src/main/java/com/adit/backend/domain/user/principal/PrincipalDetails.java
  src/main/java/com/adit/backend/domain/user/repository/FriendshipRepository.java
  src/main/java/com/adit/backend/domain/user/repository/UserRepository.java
  src/main/java/com/adit/backend/domain/user/service/FriendshipService.java
  src/main/java/com/adit/backend/domain/user/service/command/FriendCommandService.java
  src/main/java/com/adit/backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/adit/backend/domain/user/service/query/FriendQueryService.java
  src/main/java/com/adit/backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/adit/backend/global/error/GlobalErrorCode.java
  src/main/java/com/adit/backend/global/error/GlobalExceptionHandler.java
Labels: ✨ Feat
